# Generated by Django 3.2.6 on 2021-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyfall', '0002_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='refresh_room',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
