# Generated by Django 3.2.6 on 2021-09-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyfall', '0004_alter_players_refresh_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='roles_ratio',
            field=models.CharField(default='8/8', max_length=200),
        ),
    ]
