# Generated by Django 3.2.6 on 2021-10-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spyfall', '0005_players_roles_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='roles_ratio',
        ),
    ]
