# Generated by Django 3.2.6 on 2021-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyfall', '0007_players_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='end_time',
            field=models.CharField(default=156, max_length=200),
            preserve_default=False,
        ),
    ]
