# Generated by Django 3.2.6 on 2021-10-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyfall', '0008_players_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='pause_time',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
